ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
  application {
    modules = [
      com.glassbox.HttpKt.configureHttp
      com.glassbox.SerializationKt.configureSerialization
      com.glassbox.SseKt.configureSse
      com.glassbox.RoutingKt.configureRouting
    ]
  }
}